# Generated by Django 4.0.5 on 2022-12-01 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_delete_galery_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modifiy_at', models.DateTimeField(auto_now=True)),
                ('active_at', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nota', models.CharField(max_length=100, verbose_name='Nota')),
                ('aluno', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
