# Generated by Django 4.0.5 on 2022-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disciplina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nota',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Português', 'Português'), ('Biologia', 'Biologia'), ('Física', 'Física')], max_length=100, verbose_name='Nota'),
        ),
    ]
