# Generated by Django 4.0.5 on 2022-12-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_disciplina_options_alter_disciplina_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Português', 'Português'), ('Biologia', 'Biologia'), ('Física', 'Física')], max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nota',
            field=models.CharField(max_length=100, verbose_name='Nota'),
        ),
    ]
